import PERMISSIONS from "./permissions";

// Base role permissions
const PARTNER_PERMISSIONS = [
  PERMISSIONS.VIEW_CONTENT,
  PERMISSIONS.UPDATE_OWN_PROFILE,
  PERMISSIONS.COMMENT_VOTE_FEATURE_REQUESTS,
];

const CONTENTSTACK_PERMISSIONS = [
  ...PARTNER_PERMISSIONS,
  PERMISSIONS.PUBLISH_FEATURE_REQUESTS,
  PERMISSIONS.UPLOAD_INSTRUCTIONS,
  PERMISSIONS.UPLOAD_DEMO_WEBSITES,
  PERMISSIONS.UPLOAD_VIDEO_LIBRARY,
  PERMISSIONS.UPLOAD_ASSET,
  PERMISSIONS.UPDATE_LIBRARY,
  PERMISSIONS.UPLOAD_NOTIFICATIONS
];

const ADMIN_PERMISSIONS = [
  ...CONTENTSTACK_PERMISSIONS,
  PERMISSIONS.USE_PERSONAS,
  PERMISSIONS.MANAGE_USERS,
];

const ROLE_PERMISSIONS = {
  partner: PARTNER_PERMISSIONS,
  contentstack: CONTENTSTACK_PERMISSIONS,
  admin: ADMIN_PERMISSIONS,
};



export default ROLE_PERMISSIONS;

export const ROLES = Object.keys(ROLE_PERMISSIONS);

export const isValidRole = (role) =>
  ROLES.includes(role);

