name: CI

on:
  pull_request:
    branches: [main, prod]
  push:
    branches: [main, prod]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "bsu-portal-example/package-lock.json"

      - name: Install dependencies
        working-directory: bsu-portal-example
        run: npm ci

      - name: Run tests
        working-directory: bsu-portal-example
        run: npm test