name: CI

on:
  pull_request:
    branches: [main, prod]
  push:
    branches: [main, prod]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug repo root
        run: |
          pwd
          ls -la
          echo "----"
          test -f package-lock.json && echo "lockfile exists" || echo "lockfile MISSING"


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Print Working Directory
        run: pwd

      - name: List Files
        working-directory: bsu-portal-example
        run: ls -la

      - name: Run tests
        working-directory: bsu-portal-example
        run: npm test
